version: '3.8'

services:
  # BESS-Simulation Hauptanwendung
  bess-simulation:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///instance/bess.db
    volumes:
      - ./instance:/app/instance
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - bess-network

  # Redis für Caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - bess-network
    command: redis-server --appendonly yes

  # Optional: PostgreSQL (für Produktion)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=bess_simulation
  #     - POSTGRES_USER=bess_user
  #     - POSTGRES_PASSWORD=bess_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - bess-network

volumes:
  redis-data:
  # postgres-data:

networks:
  bess-network:
    driver: bridge
